markdown: rdiscount
pygments: true
permalink: /:year/:month/:day/:title
auto: true
rdiscount:
  extensions: [smart]

name: Rodrigo Lazoti
url: http://rodrigolazoti.com.br
description: Software development, technology, and cool stuff
twitter: rodrigolazoti
github: rlazoti
facebook: rodrigolazoti
linkedin: rodrigolazoti
google_plus: 111551725687201434613
app_store: mememize!/id451228425
foursquare: rodrigolazoti
instagram: rodrigolazoti
gravatar_url: http://www.gravatar.com/avatar/d6cd131c2a59ae04ca2a41f9b6825b24.png